export type Medication = {
  id: number;
  active_ingredient_id: number | null;
  brand_name: string;
  active_ingredient: string;
  commercial_aliases: string[];
  therapeutic_class: string;
  therapeutic_classes: string[];
  source_jurisdiction: string;
  evidence_source_type: string;
  validation_status: string;
  concentration: string | null;
  pharmaceutical_form: string | null;
  evidence_source_url: string | null;
  max_daily_dose_mg: number;
  max_duration_days: number | null;
  max_cumulative_dose_mg: number | null;
  continuous_use: boolean;
  monitoring_required: boolean;
  monitoring_notes: string | null;
  condition_specific_limits: Record<string, number>;
  allowed_routes: string[];
  contraindications: string[];
  renal_caution: boolean;
  hepatic_caution: boolean;
  cardiac_caution: boolean;
  gastrointestinal_caution: boolean;
  elderly_caution: boolean;
  mechanism_of_action: string | null;
  absorption_notes: string | null;
  distribution_notes: string | null;
  metabolism_organs: string[];
  elimination_organs: string[];
  renal_elimination_level: string;
  hepatic_metabolism_level: string;
  cyp_interactions: string[];
  pharmacodynamic_notes: string | null;
  pharmacokinetic_notes: string | null;
  clinical_interpretation: string | null;
  neuropsychiatric_cautions: string[];
  reproductive_cautions: string[];
  organs_involved: string[];
  relevant_adverse_effects: string[];
  structured_contraindications: string[];
  therapeutic_action: string | null;
  alternative_group: string | null;
  related_medications: string[];
  knowledge_source: string | null;
  notes: string | null;
};

export type MedicationPayload = Omit<Medication, "id">;
