"""initial v0.8.6 schema

Revision ID: 3978b04e2f62
Revises:
Create Date: 2026-07-29 02:12:33.143639
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

revision: str = "3978b04e2f62"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dcb_name", sa.String(length=160), nullable=False),
        sa.Column("normalized_name", sa.String(length=160), nullable=False),
        sa.Column("synonyms", sqlite.JSON(), nullable=False),
        sa.Column("therapeutic_classes", sqlite.JSON(), nullable=False),
        sa.Column("common_brands", sqlite.JSON(), nullable=False),
        sa.Column("jurisdiction", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("validation_status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalized_name"),
    )
    op.create_index(
        op.f("ix_active_ingredients_dcb_name"), "active_ingredients", ["dcb_name"], unique=False
    )
    op.create_index(op.f("ix_active_ingredients_id"), "active_ingredients", ["id"], unique=False)
    op.create_table(
        "ai_provider_model_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model_id", sa.String(length=180), nullable=False),
        sa.Column("display_name", sa.String(length=220), nullable=False),
        sa.Column("capabilities", sqlite.JSON(), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=True),
        sa.Column("supports_json", sa.Boolean(), nullable=False),
        sa.Column("supports_structured_output", sa.Boolean(), nullable=False),
        sa.Column("supports_tools", sa.Boolean(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_provider_model_cache_id"), "ai_provider_model_cache", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_provider_model_cache_model_id"),
        "ai_provider_model_cache",
        ["model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_provider_model_cache_provider"),
        "ai_provider_model_cache",
        ["provider"],
        unique=False,
    )
    op.create_table(
        "ai_provider_runtime_states",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("degraded_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_hash", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("provider"),
    )
    op.create_table(
        "clinical_vocabulary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("label", sa.String(length=180), nullable=False),
        sa.Column("normalized_label", sa.String(length=180), nullable=False),
        sa.Column("severity_weight", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_vocabulary_category"), "clinical_vocabulary", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_vocabulary_code"), "clinical_vocabulary", ["code"], unique=False
    )
    op.create_index(op.f("ix_clinical_vocabulary_id"), "clinical_vocabulary", ["id"], unique=False)
    op.create_table(
        "emergency_protocol_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("protocol_id", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("severity", sa.String(length=40), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("jurisdiction", sa.String(length=20), nullable=False),
        sa.Column("source_name", sa.String(length=220), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("source_version", sa.String(length=160), nullable=True),
        sa.Column("validation_status", sa.String(length=40), nullable=False),
        sa.Column("reviewed_by", sa.String(length=160), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deprecated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("snapshot", sqlite.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emergency_protocol_versions_category"),
        "emergency_protocol_versions",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_versions_id"),
        "emergency_protocol_versions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_versions_is_active"),
        "emergency_protocol_versions",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_versions_protocol_id"),
        "emergency_protocol_versions",
        ["protocol_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_versions_severity"),
        "emergency_protocol_versions",
        ["severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_versions_slug"),
        "emergency_protocol_versions",
        ["slug"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_versions_validation_status"),
        "emergency_protocol_versions",
        ["validation_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_versions_version"),
        "emergency_protocol_versions",
        ["version"],
        unique=False,
    )
    op.create_table(
        "login_throttles",
        sa.Column("identifier_hash", sa.String(length=64), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("identifier_hash"),
    )
    op.create_table(
        "specialties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("demo_only", sa.Boolean(), nullable=False),
        sa.Column("requires_rqe_for_real_use", sa.Boolean(), nullable=False),
        sa.Column("credential_verification_status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_specialties_code"), "specialties", ["code"], unique=True)
    op.create_index(op.f("ix_specialties_id"), "specialties", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("email", sa.String(length=220), nullable=False),
        sa.Column("hashed_password", sa.String(length=512), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret_encrypted", sa.String(length=512), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("specialty_code", sa.String(length=80), nullable=True),
        sa.Column("crm_demo", sa.String(length=40), nullable=True),
        sa.Column("crm_uf", sa.String(length=2), nullable=True),
        sa.Column("rqe_demo", sa.String(length=40), nullable=True),
        sa.Column("credential_verification_status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_specialty_code"), "users", ["specialty_code"], unique=False)
    op.create_table(
        "ai_configuration_audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=True),
        sa.Column("external_calls_enabled", sa.Boolean(), nullable=False),
        sa.Column("result", sa.String(length=40), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_configuration_audit_logs_action"),
        "ai_configuration_audit_logs",
        ["action"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_configuration_audit_logs_id"),
        "ai_configuration_audit_logs",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_configuration_audit_logs_provider"),
        "ai_configuration_audit_logs",
        ["provider"],
        unique=False,
    )
    op.create_table(
        "ai_provider_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("encrypted_api_key", sa.Text(), nullable=True),
        sa.Column("masked_api_key", sa.String(length=80), nullable=True),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_persistent", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_provider_credentials_id"), "ai_provider_credentials", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_provider_credentials_provider"),
        "ai_provider_credentials",
        ["provider"],
        unique=True,
    )
    op.create_table(
        "ai_provider_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("selected_model", sa.String(length=160), nullable=True),
        sa.Column("enable_external_calls", sa.Boolean(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column("use_json_mode", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_provider_settings_id"), "ai_provider_settings", ["id"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_name", sa.String(length=160), nullable=True),
        sa.Column("user_email", sa.String(length=220), nullable=True),
        sa.Column("user_role", sa.String(length=40), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("risk_level", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("details", sqlite.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_events_id"), "audit_events", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_resource_type"), "audit_events", ["resource_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_risk_level"), "audit_events", ["risk_level"], unique=False
    )
    op.create_index(op.f("ix_audit_events_status"), "audit_events", ["status"], unique=False)
    op.create_table(
        "cds_idempotency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_payload", sqlite.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "idempotency_key"),
    )
    op.create_index(
        op.f("ix_cds_idempotency_user_id"), "cds_idempotency", ["user_id"], unique=False
    )
    op.create_table(
        "drug_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active_ingredient_id", sa.Integer(), nullable=False),
        sa.Column("commercial_name", sa.String(length=160), nullable=False),
        sa.Column("manufacturer", sa.String(length=160), nullable=True),
        sa.Column("concentration", sa.String(length=120), nullable=True),
        sa.Column("pharmaceutical_form", sa.String(length=120), nullable=True),
        sa.Column("allowed_routes", sqlite.JSON(), nullable=False),
        sa.Column("anvisa_registration_number", sa.String(length=80), nullable=True),
        sa.Column("bula_url", sa.String(length=500), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("validation_status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_ingredient_id"],
            ["active_ingredients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_drug_products_active_ingredient_id"),
        "drug_products",
        ["active_ingredient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_drug_products_commercial_name"), "drug_products", ["commercial_name"], unique=False
    )
    op.create_index(op.f("ix_drug_products_id"), "drug_products", ["id"], unique=False)
    op.create_table(
        "generated_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_type", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.String(length=80), nullable=False),
        sa.Column("generated_by_user_id", sa.Integer(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("template_version", sa.String(length=80), nullable=False),
        sa.Column("prescripta_version", sa.String(length=40), nullable=False),
        sa.Column("evidence_bundle_hash", sa.String(length=128), nullable=False),
        sa.Column("ai_provider", sa.String(length=80), nullable=True),
        sa.Column("ai_model", sa.String(length=160), nullable=True),
        sa.Column("ai_prompt_version", sa.String(length=120), nullable=True),
        sa.Column("ai_used", sa.Boolean(), nullable=False),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column("anonymized", sa.Boolean(), nullable=False),
        sa.Column("file_hash", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("metadata_json", sqlite.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["generated_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generated_reports_evidence_bundle_hash"),
        "generated_reports",
        ["evidence_bundle_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generated_reports_generated_by_user_id"),
        "generated_reports",
        ["generated_by_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_generated_reports_id"), "generated_reports", ["id"], unique=False)
    op.create_index(
        op.f("ix_generated_reports_report_type"), "generated_reports", ["report_type"], unique=False
    )
    op.create_index(
        op.f("ix_generated_reports_target_id"), "generated_reports", ["target_id"], unique=False
    )
    op.create_index(
        op.f("ix_generated_reports_target_type"), "generated_reports", ["target_type"], unique=False
    )
    op.create_table(
        "medication_knowledge_curation_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query", sa.String(length=180), nullable=False),
        sa.Column("source_name", sa.String(length=180), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("source_text_excerpt", sa.Text(), nullable=False),
        sa.Column("extracted_payload", sqlite.JSON(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=True),
        sa.Column("validation_status", sa.String(length=40), nullable=False),
        sa.Column("review_status", sa.String(length=40), nullable=False),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medication_knowledge_curation_queue_id"),
        "medication_knowledge_curation_queue",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_knowledge_curation_queue_query"),
        "medication_knowledge_curation_queue",
        ["query"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_knowledge_curation_queue_review_status"),
        "medication_knowledge_curation_queue",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_knowledge_curation_queue_validation_status"),
        "medication_knowledge_curation_queue",
        ["validation_status"],
        unique=False,
    )
    op.create_table(
        "medications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active_ingredient_id", sa.Integer(), nullable=True),
        sa.Column("brand_name", sa.String(length=160), nullable=False),
        sa.Column("active_ingredient", sa.String(length=160), nullable=False),
        sa.Column("commercial_aliases", sqlite.JSON(), nullable=False),
        sa.Column("therapeutic_class", sa.String(length=160), nullable=False),
        sa.Column("therapeutic_classes", sqlite.JSON(), nullable=False),
        sa.Column("source_jurisdiction", sa.String(length=20), nullable=False),
        sa.Column("evidence_source_type", sa.String(length=80), nullable=False),
        sa.Column("validation_status", sa.String(length=40), nullable=False),
        sa.Column("concentration", sa.String(length=120), nullable=True),
        sa.Column("pharmaceutical_form", sa.String(length=120), nullable=True),
        sa.Column("evidence_source_url", sa.String(length=500), nullable=True),
        sa.Column("max_daily_dose_mg", sa.Float(), nullable=False),
        sa.Column("dose_dimension", sa.String(length=40), nullable=False),
        sa.Column("max_daily_dose_unit", sa.String(length=40), nullable=False),
        sa.Column("dose_mg_per_kg", sa.Float(), nullable=True),
        sa.Column("dose_by_weight_enabled", sa.Boolean(), nullable=False),
        sa.Column("usual_dose_low", sa.Float(), nullable=True),
        sa.Column("usual_dose_high", sa.Float(), nullable=True),
        sa.Column("max_single_dose", sa.Float(), nullable=True),
        sa.Column("max_per_procedure", sa.Float(), nullable=True),
        sa.Column("max_per_procedure_unit", sa.String(length=40), nullable=True),
        sa.Column("max_rate", sa.Float(), nullable=True),
        sa.Column("rate_unit", sa.String(length=40), nullable=True),
        sa.Column("dose_calculation_basis", sa.String(length=40), nullable=False),
        sa.Column("dose_unit", sa.String(length=40), nullable=False),
        sa.Column("dose_rule_validation_status", sa.String(length=40), nullable=False),
        sa.Column("dose_source_refs", sqlite.JSON(), nullable=False),
        sa.Column("controlled_substance", sa.Boolean(), nullable=False),
        sa.Column("controlled_substance_list", sa.String(length=80), nullable=True),
        sa.Column("prescription_form_type", sa.String(length=100), nullable=True),
        sa.Column("high_alert_category", sa.String(length=100), nullable=True),
        sa.Column("recommended_specialty_codes", sqlite.JSON(), nullable=False),
        sa.Column("required_specialty_codes", sqlite.JSON(), nullable=False),
        sa.Column("requires_second_review", sa.Boolean(), nullable=False),
        sa.Column("requires_institutional_protocol", sa.Boolean(), nullable=False),
        sa.Column("policy_type", sa.String(length=60), nullable=False),
        sa.Column("policy_strength", sa.String(length=40), nullable=False),
        sa.Column("policy_validation_status", sa.String(length=40), nullable=False),
        sa.Column("policy_source_refs", sqlite.JSON(), nullable=False),
        sa.Column("policy_version", sa.String(length=40), nullable=False),
        sa.Column("source_version", sa.String(length=80), nullable=True),
        sa.Column("institution_id", sa.String(length=100), nullable=True),
        sa.Column("policy_effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("policy_effective_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("override_allowed", sa.Boolean(), nullable=False),
        sa.Column("override_reason_required", sa.Boolean(), nullable=False),
        sa.Column("second_reviewer_role", sa.String(length=40), nullable=True),
        sa.Column("psychotropic_class", sa.String(length=100), nullable=True),
        sa.Column("psychotropic_profile", sqlite.JSON(), nullable=False),
        sa.Column("max_duration_days", sa.Integer(), nullable=True),
        sa.Column("max_cumulative_dose_mg", sa.Float(), nullable=True),
        sa.Column("continuous_use", sa.Boolean(), nullable=False),
        sa.Column("monitoring_required", sa.Boolean(), nullable=False),
        sa.Column("monitoring_notes", sa.Text(), nullable=True),
        sa.Column("condition_specific_limits", sqlite.JSON(), nullable=False),
        sa.Column("allowed_routes", sqlite.JSON(), nullable=False),
        sa.Column("contraindications", sqlite.JSON(), nullable=False),
        sa.Column("renal_caution", sa.Boolean(), nullable=False),
        sa.Column("hepatic_caution", sa.Boolean(), nullable=False),
        sa.Column("cardiac_caution", sa.Boolean(), nullable=False),
        sa.Column("gastrointestinal_caution", sa.Boolean(), nullable=False),
        sa.Column("elderly_caution", sa.Boolean(), nullable=False),
        sa.Column("mechanism_of_action", sa.Text(), nullable=True),
        sa.Column("absorption_notes", sa.Text(), nullable=True),
        sa.Column("distribution_notes", sa.Text(), nullable=True),
        sa.Column("metabolism_organs", sqlite.JSON(), nullable=False),
        sa.Column("elimination_organs", sqlite.JSON(), nullable=False),
        sa.Column("renal_elimination_level", sa.String(length=40), nullable=False),
        sa.Column("hepatic_metabolism_level", sa.String(length=40), nullable=False),
        sa.Column("cyp_interactions", sqlite.JSON(), nullable=False),
        sa.Column("pharmacodynamic_notes", sa.Text(), nullable=True),
        sa.Column("pharmacokinetic_notes", sa.Text(), nullable=True),
        sa.Column("clinical_interpretation", sa.Text(), nullable=True),
        sa.Column("neuropsychiatric_cautions", sqlite.JSON(), nullable=False),
        sa.Column("reproductive_cautions", sqlite.JSON(), nullable=False),
        sa.Column("organs_involved", sqlite.JSON(), nullable=False),
        sa.Column("relevant_adverse_effects", sqlite.JSON(), nullable=False),
        sa.Column("structured_contraindications", sqlite.JSON(), nullable=False),
        sa.Column("therapeutic_action", sa.String(length=180), nullable=True),
        sa.Column("alternative_group", sa.String(length=120), nullable=True),
        sa.Column("related_medications", sqlite.JSON(), nullable=False),
        sa.Column("knowledge_source", sa.String(length=220), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["active_ingredient_id"],
            ["active_ingredients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medications_active_ingredient"), "medications", ["active_ingredient"], unique=False
    )
    op.create_index(
        op.f("ix_medications_active_ingredient_id"),
        "medications",
        ["active_ingredient_id"],
        unique=False,
    )
    op.create_index(op.f("ix_medications_brand_name"), "medications", ["brand_name"], unique=False)
    op.create_index(op.f("ix_medications_id"), "medications", ["id"], unique=False)
    op.create_table(
        "patients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("sex_for_dosing_calculation", sa.String(length=20), nullable=True),
        sa.Column("phone", sa.String(length=80), nullable=True),
        sa.Column("email", sa.String(length=220), nullable=True),
        sa.Column("mother_name", sa.String(length=160), nullable=True),
        sa.Column("allergies", sqlite.JSON(), nullable=False),
        sa.Column("comorbidities", sqlite.JSON(), nullable=False),
        sa.Column("current_medications", sqlite.JSON(), nullable=False),
        sa.Column("renal_condition", sa.String(length=120), nullable=True),
        sa.Column("hepatic_condition", sa.String(length=120), nullable=True),
        sa.Column("cardiac_condition", sa.String(length=120), nullable=True),
        sa.Column("gastrointestinal_history", sa.String(length=160), nullable=True),
        sa.Column("hypertension", sa.Boolean(), nullable=False),
        sa.Column("diabetes", sa.Boolean(), nullable=False),
        sa.Column("pregnancy_or_lactation", sa.Boolean(), nullable=True),
        sa.Column("mental_health_factors", sqlite.JSON(), nullable=False),
        sa.Column("reproductive_gynecologic_factors", sqlite.JSON(), nullable=False),
        sa.Column("adverse_reactions", sqlite.JSON(), nullable=False),
        sa.Column("clinical_notes", sa.Text(), nullable=True),
        sa.Column("clinical_profile_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("clinical_profile_completeness_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patients_created_by_user_id"), "patients", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_patients_id"), "patients", ["id"], unique=False)
    op.create_index(op.f("ix_patients_name"), "patients", ["name"], unique=False)
    op.create_table(
        "consent_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("authorized_by", sa.String(length=160), nullable=False),
        sa.Column("purpose", sa.String(length=240), nullable=False),
        sa.Column("source_system", sa.String(length=120), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_consent_records_id"), "consent_records", ["id"], unique=False)
    op.create_table(
        "emergency_protocol_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("protocol_version_id", sa.Integer(), nullable=False),
        sa.Column("protocol_id", sa.String(length=120), nullable=False),
        sa.Column("protocol_title", sa.String(length=180), nullable=False),
        sa.Column("protocol_category", sa.String(length=120), nullable=False),
        sa.Column("protocol_severity", sa.String(length=40), nullable=False),
        sa.Column("protocol_version", sa.String(length=80), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("audit_event_id", sa.Integer(), nullable=True),
        sa.Column("context", sqlite.JSON(), nullable=False),
        sa.Column("selected_step_orders", sqlite.JSON(), nullable=False),
        sa.Column("patient_context_summary", sqlite.JSON(), nullable=False),
        sa.Column("triage_flags", sqlite.JSON(), nullable=False),
        sa.Column("calculated_values", sqlite.JSON(), nullable=False),
        sa.Column("evidence_refs", sqlite.JSON(), nullable=False),
        sa.Column("timeline", sqlite.JSON(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("ai_provider", sa.String(length=80), nullable=True),
        sa.Column("ai_model", sa.String(length=160), nullable=True),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["audit_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["protocol_version_id"],
            ["emergency_protocol_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emergency_protocol_runs_id"), "emergency_protocol_runs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_emergency_protocol_runs_protocol_category"),
        "emergency_protocol_runs",
        ["protocol_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_runs_protocol_id"),
        "emergency_protocol_runs",
        ["protocol_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_runs_protocol_severity"),
        "emergency_protocol_runs",
        ["protocol_severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_runs_protocol_version"),
        "emergency_protocol_runs",
        ["protocol_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_runs_protocol_version_id"),
        "emergency_protocol_runs",
        ["protocol_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_runs_status"),
        "emergency_protocol_runs",
        ["status"],
        unique=False,
    )
    op.create_table(
        "medication_counseling_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active_ingredient_id", sa.Integer(), nullable=True),
        sa.Column("medication_id", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.String(length=160), nullable=False),
        sa.Column("jurisdiction", sa.String(length=20), nullable=False),
        sa.Column("source_name", sa.String(length=160), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("source_version", sa.String(length=120), nullable=True),
        sa.Column("validation_status", sa.String(length=40), nullable=False),
        sa.Column("generated_by", sa.String(length=40), nullable=False),
        sa.Column("provider_name", sa.String(length=80), nullable=True),
        sa.Column("confidence", sa.String(length=40), nullable=False),
        sa.Column("requires_review", sa.Boolean(), nullable=False),
        sa.Column("main_adverse_effects", sqlite.JSON(), nullable=False),
        sa.Column("patient_relevant_effects", sqlite.JSON(), nullable=False),
        sa.Column("activity_warnings", sqlite.JSON(), nullable=False),
        sa.Column("driving_warning", sa.Boolean(), nullable=False),
        sa.Column("machine_operation_warning", sa.Boolean(), nullable=False),
        sa.Column("work_at_height_warning", sa.Boolean(), nullable=False),
        sa.Column("fall_risk_warning", sa.Boolean(), nullable=False),
        sa.Column("sedation_attention_warning", sa.Boolean(), nullable=False),
        sa.Column("sleep_effects", sqlite.JSON(), nullable=False),
        sa.Column("appetite_weight_effects", sqlite.JSON(), nullable=False),
        sa.Column("mood_behavior_effects", sqlite.JSON(), nullable=False),
        sa.Column("libido_sexual_effects", sqlite.JSON(), nullable=False),
        sa.Column("neurologic_effects", sqlite.JSON(), nullable=False),
        sa.Column("tremor_warning", sa.Boolean(), nullable=False),
        sa.Column("headache_warning", sa.Boolean(), nullable=False),
        sa.Column("temperature_regulation_effects", sqlite.JSON(), nullable=False),
        sa.Column("blood_pressure_warning", sa.Boolean(), nullable=False),
        sa.Column("gastrointestinal_effects", sqlite.JSON(), nullable=False),
        sa.Column("renal_effects", sqlite.JSON(), nullable=False),
        sa.Column("hepatic_effects", sqlite.JSON(), nullable=False),
        sa.Column("reproductive_contraceptive_effects", sqlite.JSON(), nullable=False),
        sa.Column("red_flags", sqlite.JSON(), nullable=False),
        sa.Column("monitoring_required", sqlite.JSON(), nullable=False),
        sa.Column("patient_friendly_summary", sa.Text(), nullable=False),
        sa.Column("professional_summary", sa.Text(), nullable=False),
        sa.Column("extracted_evidence", sqlite.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_ingredient_id"],
            ["active_ingredients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medication_counseling_summaries_active_ingredient_id"),
        "medication_counseling_summaries",
        ["active_ingredient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_counseling_summaries_id"),
        "medication_counseling_summaries",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_counseling_summaries_medication_id"),
        "medication_counseling_summaries",
        ["medication_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_counseling_summaries_source_id"),
        "medication_counseling_summaries",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_counseling_summaries_validation_status"),
        "medication_counseling_summaries",
        ["validation_status"],
        unique=False,
    )
    op.create_table(
        "medication_knowledge_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active_ingredient_id", sa.Integer(), nullable=True),
        sa.Column("drug_product_id", sa.Integer(), nullable=True),
        sa.Column("source_name", sa.String(length=160), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("jurisdiction", sa.String(length=20), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.String(length=120), nullable=True),
        sa.Column("evidence_sections", sqlite.JSON(), nullable=False),
        sa.Column("confidence_level", sa.String(length=40), nullable=False),
        sa.Column("validation_status", sa.String(length=40), nullable=False),
        sa.Column("reviewer", sa.String(length=160), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_ingredient_id"],
            ["active_ingredients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["drug_product_id"],
            ["drug_products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medication_knowledge_sources_active_ingredient_id"),
        "medication_knowledge_sources",
        ["active_ingredient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_knowledge_sources_drug_product_id"),
        "medication_knowledge_sources",
        ["drug_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_knowledge_sources_id"),
        "medication_knowledge_sources",
        ["id"],
        unique=False,
    )
    op.create_table(
        "patient_access_grants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("permission", sa.String(length=40), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=220), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("patient_id", "user_id", "permission"),
    )
    op.create_index(
        op.f("ix_patient_access_grants_patient_id"),
        "patient_access_grants",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_access_grants_user_id"), "patient_access_grants", ["user_id"], unique=False
    )
    op.create_table(
        "patient_clinical_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("document_type", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("source_system", sa.String(length=120), nullable=True),
        sa.Column("document_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("structured_payload", sqlite.JSON(), nullable=False),
        sa.Column("extracted_entities", sqlite.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("validation_status", sa.String(length=40), nullable=False),
        sa.Column("review_status", sa.String(length=40), nullable=False),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_hash", sa.String(length=128), nullable=True),
        sa.Column("storage_path", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patient_clinical_documents_file_hash"),
        "patient_clinical_documents",
        ["file_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_clinical_documents_id"), "patient_clinical_documents", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_patient_clinical_documents_patient_id"),
        "patient_clinical_documents",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_clinical_documents_review_status"),
        "patient_clinical_documents",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_clinical_documents_validation_status"),
        "patient_clinical_documents",
        ["validation_status"],
        unique=False,
    )
    op.create_table(
        "patient_clinical_timeline_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("source_system", sa.String(length=120), nullable=True),
        sa.Column("event_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", sqlite.JSON(), nullable=False),
        sa.Column("validation_status", sa.String(length=40), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patient_clinical_timeline_events_event_type"),
        "patient_clinical_timeline_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_clinical_timeline_events_id"),
        "patient_clinical_timeline_events",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_clinical_timeline_events_patient_id"),
        "patient_clinical_timeline_events",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_clinical_timeline_events_validation_status"),
        "patient_clinical_timeline_events",
        ["validation_status"],
        unique=False,
    )
    op.create_table(
        "patient_functional_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("drives_regularly", sa.Boolean(), nullable=True),
        sa.Column("professional_driver", sa.Boolean(), nullable=True),
        sa.Column("operates_machinery", sa.Boolean(), nullable=True),
        sa.Column("works_at_height", sa.Boolean(), nullable=True),
        sa.Column("fall_risk_activity", sa.Boolean(), nullable=True),
        sa.Column("night_shift", sa.Boolean(), nullable=True),
        sa.Column("caregiver_responsibility", sa.Boolean(), nullable=True),
        sa.Column("high_attention_activity", sa.Boolean(), nullable=True),
        sa.Column("frequent_alcohol_use", sa.Boolean(), nullable=True),
        sa.Column("history_of_falls", sa.Boolean(), nullable=True),
        sa.Column("low_tolerance_to_sedation_or_dizziness", sa.Boolean(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patient_functional_profiles_id"),
        "patient_functional_profiles",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_functional_profiles_patient_id"),
        "patient_functional_profiles",
        ["patient_id"],
        unique=True,
    )
    op.create_table(
        "patient_identifiers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("identifier_type", sa.String(length=80), nullable=False),
        sa.Column("identifier_value_hash", sa.String(length=128), nullable=False),
        sa.Column("issuing_system", sa.String(length=160), nullable=True),
        sa.Column("display_masked", sa.String(length=80), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patient_identifiers_id"), "patient_identifiers", ["id"], unique=False)
    op.create_index(
        op.f("ix_patient_identifiers_identifier_type"),
        "patient_identifiers",
        ["identifier_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_identifiers_identifier_value_hash"),
        "patient_identifiers",
        ["identifier_value_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_identifiers_patient_id"),
        "patient_identifiers",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "prescription_audits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("medication_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_name", sa.String(length=160), nullable=True),
        sa.Column("user_email", sa.String(length=220), nullable=True),
        sa.Column("patient_name", sa.String(length=160), nullable=False),
        sa.Column("medication_name", sa.String(length=160), nullable=False),
        sa.Column("dose_mg", sa.Float(), nullable=True),
        sa.Column("frequency_per_day", sa.Integer(), nullable=True),
        sa.Column("route", sa.String(length=80), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("indication", sa.String(length=180), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("risk_level", sa.String(length=40), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("alerts", sqlite.JSON(), nullable=False),
        sa.Column("dose_intelligence", sqlite.JSON(), nullable=False),
        sa.Column("psychotropic_safety", sqlite.JSON(), nullable=False),
        sa.Column("prescribing_policy", sqlite.JSON(), nullable=False),
        sa.Column("dose_input", sqlite.JSON(), nullable=False),
        sa.Column("clinical_decision", sqlite.JSON(), nullable=False),
        sa.Column("clinical_snapshot", sqlite.JSON(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("hash_algorithm", sa.String(length=80), nullable=True),
        sa.Column("snapshot_schema_version", sa.String(length=80), nullable=True),
        sa.Column("correlation_id", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prescription_audits_correlation_id"),
        "prescription_audits",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_prescription_audits_id"), "prescription_audits", ["id"], unique=False)
    op.create_index(
        op.f("ix_prescription_audits_snapshot_hash"),
        "prescription_audits",
        ["snapshot_hash"],
        unique=False,
    )
    op.create_table(
        "clinical_import_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_system", sa.String(length=120), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("imported_by", sa.Integer(), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("consent_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("errors", sqlite.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["consent_id"],
            ["consent_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["imported_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_import_batches_id"), "clinical_import_batches", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_import_batches_source_system"),
        "clinical_import_batches",
        ["source_system"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_import_batches_source_type"),
        "clinical_import_batches",
        ["source_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_import_batches_status"),
        "clinical_import_batches",
        ["status"],
        unique=False,
    )
    op.create_table(
        "decision_overrides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prescription_audit_id", sa.Integer(), nullable=False),
        sa.Column("requested_by_user_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("review_decision", sa.String(length=40), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["prescription_audit_id"],
            ["prescription_audits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prescription_audit_id"),
    )
    op.create_index(op.f("ix_decision_overrides_id"), "decision_overrides", ["id"], unique=False)
    op.create_index(
        op.f("ix_decision_overrides_prescription_audit_id"),
        "decision_overrides",
        ["prescription_audit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_overrides_requested_by_user_id"),
        "decision_overrides",
        ["requested_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_overrides_reviewed_by_user_id"),
        "decision_overrides",
        ["reviewed_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_overrides_status"), "decision_overrides", ["status"], unique=False
    )
    op.create_table(
        "emergency_protocol_run_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("generated_report_id", sa.Integer(), nullable=False),
        sa.Column("report_type", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["generated_report_id"],
            ["generated_reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["emergency_protocol_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emergency_protocol_run_reports_generated_report_id"),
        "emergency_protocol_run_reports",
        ["generated_report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_run_reports_id"),
        "emergency_protocol_run_reports",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_run_reports_run_id"),
        "emergency_protocol_run_reports",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "emergency_protocol_run_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("evidence_ref", sa.String(length=120), nullable=False),
        sa.Column("checked", sa.Boolean(), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["emergency_protocol_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emergency_protocol_run_steps_id"),
        "emergency_protocol_run_steps",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emergency_protocol_run_steps_run_id"),
        "emergency_protocol_run_steps",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "patient_document_extractions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=True),
        sa.Column("extracted_entities", sqlite.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("validation_status", sa.String(length=40), nullable=False),
        sa.Column("review_status", sa.String(length=40), nullable=False),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["patient_clinical_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patient_document_extractions_document_id"),
        "patient_document_extractions",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_document_extractions_id"),
        "patient_document_extractions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_document_extractions_patient_id"),
        "patient_document_extractions",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_document_extractions_review_status"),
        "patient_document_extractions",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_document_extractions_validation_status"),
        "patient_document_extractions",
        ["validation_status"],
        unique=False,
    )
    op.create_table(
        "patient_medication_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("medication_name", sa.String(length=180), nullable=False),
        sa.Column("active_ingredient", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("source_document_id", sa.Integer(), nullable=True),
        sa.Column("validation_status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["patient_clinical_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patient_medication_history_id"), "patient_medication_history", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_patient_medication_history_medication_name"),
        "patient_medication_history",
        ["medication_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_medication_history_patient_id"),
        "patient_medication_history",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "clinical_source_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("record_type", sa.String(length=80), nullable=False),
        sa.Column("source_payload", sqlite.JSON(), nullable=False),
        sa.Column("mapped_payload", sqlite.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("accepted_by_user", sa.Boolean(), nullable=False),
        sa.Column("rejected_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["clinical_import_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_source_records_batch_id"),
        "clinical_source_records",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_source_records_id"), "clinical_source_records", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_source_records_record_type"),
        "clinical_source_records",
        ["record_type"],
        unique=False,
    )
    op.create_table(
        "integration_audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("source_system", sa.String(length=120), nullable=False),
        sa.Column("details", sqlite.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["clinical_import_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_integration_audit_logs_action"), "integration_audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_integration_audit_logs_id"), "integration_audit_logs", ["id"], unique=False
    )
    op.create_table(
        "clinical_reconciliation_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("source_record_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.String(length=160), nullable=False),
        sa.Column("record_type", sa.String(length=80), nullable=False),
        sa.Column("field_path", sa.String(length=160), nullable=False),
        sa.Column("current_value", sqlite.JSON(), nullable=False),
        sa.Column("imported_value", sqlite.JSON(), nullable=False),
        sa.Column("source_system", sa.String(length=120), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("badge", sa.String(length=40), nullable=False),
        sa.Column("suggestion", sa.String(length=80), nullable=False),
        sa.Column("decision", sa.String(length=40), nullable=True),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["clinical_import_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["clinical_source_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_reconciliation_decisions_batch_id"),
        "clinical_reconciliation_decisions",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_reconciliation_decisions_id"),
        "clinical_reconciliation_decisions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_reconciliation_decisions_item_id"),
        "clinical_reconciliation_decisions",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_reconciliation_decisions_record_type"),
        "clinical_reconciliation_decisions",
        ["record_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_reconciliation_decisions_source_record_id"),
        "clinical_reconciliation_decisions",
        ["source_record_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_clinical_reconciliation_decisions_source_record_id"),
        table_name="clinical_reconciliation_decisions",
    )
    op.drop_index(
        op.f("ix_clinical_reconciliation_decisions_record_type"),
        table_name="clinical_reconciliation_decisions",
    )
    op.drop_index(
        op.f("ix_clinical_reconciliation_decisions_item_id"),
        table_name="clinical_reconciliation_decisions",
    )
    op.drop_index(
        op.f("ix_clinical_reconciliation_decisions_id"),
        table_name="clinical_reconciliation_decisions",
    )
    op.drop_index(
        op.f("ix_clinical_reconciliation_decisions_batch_id"),
        table_name="clinical_reconciliation_decisions",
    )
    op.drop_table("clinical_reconciliation_decisions")
    op.drop_index(op.f("ix_integration_audit_logs_id"), table_name="integration_audit_logs")
    op.drop_index(op.f("ix_integration_audit_logs_action"), table_name="integration_audit_logs")
    op.drop_table("integration_audit_logs")
    op.drop_index(
        op.f("ix_clinical_source_records_record_type"), table_name="clinical_source_records"
    )
    op.drop_index(op.f("ix_clinical_source_records_id"), table_name="clinical_source_records")
    op.drop_index(op.f("ix_clinical_source_records_batch_id"), table_name="clinical_source_records")
    op.drop_table("clinical_source_records")
    op.drop_index(
        op.f("ix_patient_medication_history_patient_id"), table_name="patient_medication_history"
    )
    op.drop_index(
        op.f("ix_patient_medication_history_medication_name"),
        table_name="patient_medication_history",
    )
    op.drop_index(op.f("ix_patient_medication_history_id"), table_name="patient_medication_history")
    op.drop_table("patient_medication_history")
    op.drop_index(
        op.f("ix_patient_document_extractions_validation_status"),
        table_name="patient_document_extractions",
    )
    op.drop_index(
        op.f("ix_patient_document_extractions_review_status"),
        table_name="patient_document_extractions",
    )
    op.drop_index(
        op.f("ix_patient_document_extractions_patient_id"),
        table_name="patient_document_extractions",
    )
    op.drop_index(
        op.f("ix_patient_document_extractions_id"), table_name="patient_document_extractions"
    )
    op.drop_index(
        op.f("ix_patient_document_extractions_document_id"),
        table_name="patient_document_extractions",
    )
    op.drop_table("patient_document_extractions")
    op.drop_index(
        op.f("ix_emergency_protocol_run_steps_run_id"), table_name="emergency_protocol_run_steps"
    )
    op.drop_index(
        op.f("ix_emergency_protocol_run_steps_id"), table_name="emergency_protocol_run_steps"
    )
    op.drop_table("emergency_protocol_run_steps")
    op.drop_index(
        op.f("ix_emergency_protocol_run_reports_run_id"),
        table_name="emergency_protocol_run_reports",
    )
    op.drop_index(
        op.f("ix_emergency_protocol_run_reports_id"), table_name="emergency_protocol_run_reports"
    )
    op.drop_index(
        op.f("ix_emergency_protocol_run_reports_generated_report_id"),
        table_name="emergency_protocol_run_reports",
    )
    op.drop_table("emergency_protocol_run_reports")
    op.drop_index(op.f("ix_decision_overrides_status"), table_name="decision_overrides")
    op.drop_index(
        op.f("ix_decision_overrides_reviewed_by_user_id"), table_name="decision_overrides"
    )
    op.drop_index(
        op.f("ix_decision_overrides_requested_by_user_id"), table_name="decision_overrides"
    )
    op.drop_index(
        op.f("ix_decision_overrides_prescription_audit_id"), table_name="decision_overrides"
    )
    op.drop_index(op.f("ix_decision_overrides_id"), table_name="decision_overrides")
    op.drop_table("decision_overrides")
    op.drop_index(op.f("ix_clinical_import_batches_status"), table_name="clinical_import_batches")
    op.drop_index(
        op.f("ix_clinical_import_batches_source_type"), table_name="clinical_import_batches"
    )
    op.drop_index(
        op.f("ix_clinical_import_batches_source_system"), table_name="clinical_import_batches"
    )
    op.drop_index(op.f("ix_clinical_import_batches_id"), table_name="clinical_import_batches")
    op.drop_table("clinical_import_batches")
    op.drop_index(op.f("ix_prescription_audits_snapshot_hash"), table_name="prescription_audits")
    op.drop_index(op.f("ix_prescription_audits_id"), table_name="prescription_audits")
    op.drop_index(op.f("ix_prescription_audits_correlation_id"), table_name="prescription_audits")
    op.drop_table("prescription_audits")
    op.drop_index(op.f("ix_patient_identifiers_patient_id"), table_name="patient_identifiers")
    op.drop_index(
        op.f("ix_patient_identifiers_identifier_value_hash"), table_name="patient_identifiers"
    )
    op.drop_index(op.f("ix_patient_identifiers_identifier_type"), table_name="patient_identifiers")
    op.drop_index(op.f("ix_patient_identifiers_id"), table_name="patient_identifiers")
    op.drop_table("patient_identifiers")
    op.drop_index(
        op.f("ix_patient_functional_profiles_patient_id"), table_name="patient_functional_profiles"
    )
    op.drop_index(
        op.f("ix_patient_functional_profiles_id"), table_name="patient_functional_profiles"
    )
    op.drop_table("patient_functional_profiles")
    op.drop_index(
        op.f("ix_patient_clinical_timeline_events_validation_status"),
        table_name="patient_clinical_timeline_events",
    )
    op.drop_index(
        op.f("ix_patient_clinical_timeline_events_patient_id"),
        table_name="patient_clinical_timeline_events",
    )
    op.drop_index(
        op.f("ix_patient_clinical_timeline_events_id"),
        table_name="patient_clinical_timeline_events",
    )
    op.drop_index(
        op.f("ix_patient_clinical_timeline_events_event_type"),
        table_name="patient_clinical_timeline_events",
    )
    op.drop_table("patient_clinical_timeline_events")
    op.drop_index(
        op.f("ix_patient_clinical_documents_validation_status"),
        table_name="patient_clinical_documents",
    )
    op.drop_index(
        op.f("ix_patient_clinical_documents_review_status"), table_name="patient_clinical_documents"
    )
    op.drop_index(
        op.f("ix_patient_clinical_documents_patient_id"), table_name="patient_clinical_documents"
    )
    op.drop_index(op.f("ix_patient_clinical_documents_id"), table_name="patient_clinical_documents")
    op.drop_index(
        op.f("ix_patient_clinical_documents_file_hash"), table_name="patient_clinical_documents"
    )
    op.drop_table("patient_clinical_documents")
    op.drop_index(op.f("ix_patient_access_grants_user_id"), table_name="patient_access_grants")
    op.drop_index(op.f("ix_patient_access_grants_patient_id"), table_name="patient_access_grants")
    op.drop_table("patient_access_grants")
    op.drop_index(
        op.f("ix_medication_knowledge_sources_id"), table_name="medication_knowledge_sources"
    )
    op.drop_index(
        op.f("ix_medication_knowledge_sources_drug_product_id"),
        table_name="medication_knowledge_sources",
    )
    op.drop_index(
        op.f("ix_medication_knowledge_sources_active_ingredient_id"),
        table_name="medication_knowledge_sources",
    )
    op.drop_table("medication_knowledge_sources")
    op.drop_index(
        op.f("ix_medication_counseling_summaries_validation_status"),
        table_name="medication_counseling_summaries",
    )
    op.drop_index(
        op.f("ix_medication_counseling_summaries_source_id"),
        table_name="medication_counseling_summaries",
    )
    op.drop_index(
        op.f("ix_medication_counseling_summaries_medication_id"),
        table_name="medication_counseling_summaries",
    )
    op.drop_index(
        op.f("ix_medication_counseling_summaries_id"), table_name="medication_counseling_summaries"
    )
    op.drop_index(
        op.f("ix_medication_counseling_summaries_active_ingredient_id"),
        table_name="medication_counseling_summaries",
    )
    op.drop_table("medication_counseling_summaries")
    op.drop_index(op.f("ix_emergency_protocol_runs_status"), table_name="emergency_protocol_runs")
    op.drop_index(
        op.f("ix_emergency_protocol_runs_protocol_version_id"), table_name="emergency_protocol_runs"
    )
    op.drop_index(
        op.f("ix_emergency_protocol_runs_protocol_version"), table_name="emergency_protocol_runs"
    )
    op.drop_index(
        op.f("ix_emergency_protocol_runs_protocol_severity"), table_name="emergency_protocol_runs"
    )
    op.drop_index(
        op.f("ix_emergency_protocol_runs_protocol_id"), table_name="emergency_protocol_runs"
    )
    op.drop_index(
        op.f("ix_emergency_protocol_runs_protocol_category"), table_name="emergency_protocol_runs"
    )
    op.drop_index(op.f("ix_emergency_protocol_runs_id"), table_name="emergency_protocol_runs")
    op.drop_table("emergency_protocol_runs")
    op.drop_index(op.f("ix_consent_records_id"), table_name="consent_records")
    op.drop_table("consent_records")
    op.drop_index(op.f("ix_patients_name"), table_name="patients")
    op.drop_index(op.f("ix_patients_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_created_by_user_id"), table_name="patients")
    op.drop_table("patients")
    op.drop_index(op.f("ix_medications_id"), table_name="medications")
    op.drop_index(op.f("ix_medications_brand_name"), table_name="medications")
    op.drop_index(op.f("ix_medications_active_ingredient_id"), table_name="medications")
    op.drop_index(op.f("ix_medications_active_ingredient"), table_name="medications")
    op.drop_table("medications")
    op.drop_index(
        op.f("ix_medication_knowledge_curation_queue_validation_status"),
        table_name="medication_knowledge_curation_queue",
    )
    op.drop_index(
        op.f("ix_medication_knowledge_curation_queue_review_status"),
        table_name="medication_knowledge_curation_queue",
    )
    op.drop_index(
        op.f("ix_medication_knowledge_curation_queue_query"),
        table_name="medication_knowledge_curation_queue",
    )
    op.drop_index(
        op.f("ix_medication_knowledge_curation_queue_id"),
        table_name="medication_knowledge_curation_queue",
    )
    op.drop_table("medication_knowledge_curation_queue")
    op.drop_index(op.f("ix_generated_reports_target_type"), table_name="generated_reports")
    op.drop_index(op.f("ix_generated_reports_target_id"), table_name="generated_reports")
    op.drop_index(op.f("ix_generated_reports_report_type"), table_name="generated_reports")
    op.drop_index(op.f("ix_generated_reports_id"), table_name="generated_reports")
    op.drop_index(op.f("ix_generated_reports_generated_by_user_id"), table_name="generated_reports")
    op.drop_index(op.f("ix_generated_reports_evidence_bundle_hash"), table_name="generated_reports")
    op.drop_table("generated_reports")
    op.drop_index(op.f("ix_drug_products_id"), table_name="drug_products")
    op.drop_index(op.f("ix_drug_products_commercial_name"), table_name="drug_products")
    op.drop_index(op.f("ix_drug_products_active_ingredient_id"), table_name="drug_products")
    op.drop_table("drug_products")
    op.drop_index(op.f("ix_cds_idempotency_user_id"), table_name="cds_idempotency")
    op.drop_table("cds_idempotency")
    op.drop_index(op.f("ix_audit_events_status"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_risk_level"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_resource_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_ai_provider_settings_id"), table_name="ai_provider_settings")
    op.drop_table("ai_provider_settings")
    op.drop_index(op.f("ix_ai_provider_credentials_provider"), table_name="ai_provider_credentials")
    op.drop_index(op.f("ix_ai_provider_credentials_id"), table_name="ai_provider_credentials")
    op.drop_table("ai_provider_credentials")
    op.drop_index(
        op.f("ix_ai_configuration_audit_logs_provider"), table_name="ai_configuration_audit_logs"
    )
    op.drop_index(
        op.f("ix_ai_configuration_audit_logs_id"), table_name="ai_configuration_audit_logs"
    )
    op.drop_index(
        op.f("ix_ai_configuration_audit_logs_action"), table_name="ai_configuration_audit_logs"
    )
    op.drop_table("ai_configuration_audit_logs")
    op.drop_index(op.f("ix_users_specialty_code"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_specialties_id"), table_name="specialties")
    op.drop_index(op.f("ix_specialties_code"), table_name="specialties")
    op.drop_table("specialties")
    op.drop_table("login_throttles")
    op.drop_index(
        op.f("ix_emergency_protocol_versions_version"), table_name="emergency_protocol_versions"
    )
    op.drop_index(
        op.f("ix_emergency_protocol_versions_validation_status"),
        table_name="emergency_protocol_versions",
    )
    op.drop_index(
        op.f("ix_emergency_protocol_versions_slug"), table_name="emergency_protocol_versions"
    )
    op.drop_index(
        op.f("ix_emergency_protocol_versions_severity"), table_name="emergency_protocol_versions"
    )
    op.drop_index(
        op.f("ix_emergency_protocol_versions_protocol_id"), table_name="emergency_protocol_versions"
    )
    op.drop_index(
        op.f("ix_emergency_protocol_versions_is_active"), table_name="emergency_protocol_versions"
    )
    op.drop_index(
        op.f("ix_emergency_protocol_versions_id"), table_name="emergency_protocol_versions"
    )
    op.drop_index(
        op.f("ix_emergency_protocol_versions_category"), table_name="emergency_protocol_versions"
    )
    op.drop_table("emergency_protocol_versions")
    op.drop_index(op.f("ix_clinical_vocabulary_id"), table_name="clinical_vocabulary")
    op.drop_index(op.f("ix_clinical_vocabulary_code"), table_name="clinical_vocabulary")
    op.drop_index(op.f("ix_clinical_vocabulary_category"), table_name="clinical_vocabulary")
    op.drop_table("clinical_vocabulary")
    op.drop_table("ai_provider_runtime_states")
    op.drop_index(op.f("ix_ai_provider_model_cache_provider"), table_name="ai_provider_model_cache")
    op.drop_index(op.f("ix_ai_provider_model_cache_model_id"), table_name="ai_provider_model_cache")
    op.drop_index(op.f("ix_ai_provider_model_cache_id"), table_name="ai_provider_model_cache")
    op.drop_table("ai_provider_model_cache")
    op.drop_index(op.f("ix_active_ingredients_id"), table_name="active_ingredients")
    op.drop_index(op.f("ix_active_ingredients_dcb_name"), table_name="active_ingredients")
    op.drop_table("active_ingredients")
    # ### end Alembic commands ###
