"""professional clinical workflows

Revision ID: 3cebc8f0ba12
Revises: b87a224c617e
Create Date: 2026-08-07 23:28:33.611327
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3cebc8f0ba12"
down_revision: str | Sequence[str] | None = "b87a224c617e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institutional_clinical_protocols",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("program", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_id", "code"),
    )
    op.create_index(
        op.f("ix_institutional_clinical_protocols_code"),
        "institutional_clinical_protocols",
        ["code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_institutional_clinical_protocols_id"),
        "institutional_clinical_protocols",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_institutional_clinical_protocols_institution_id"),
        "institutional_clinical_protocols",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_institutional_clinical_protocols_program"),
        "institutional_clinical_protocols",
        ["program"],
        unique=False,
    )
    op.create_index(
        op.f("ix_institutional_clinical_protocols_status"),
        "institutional_clinical_protocols",
        ["status"],
        unique=False,
    )
    op.create_table(
        "institutional_clinical_protocol_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("protocol_id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("review_status", sa.String(length=40), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_refs", sa.JSON(), nullable=False),
        sa.Column("clinical_context", sa.JSON(), nullable=False),
        sa.Column("eligible_professions", sa.JSON(), nullable=False),
        sa.Column("required_capability", sa.String(length=100), nullable=False),
        sa.Column("required_parameters", sa.JSON(), nullable=False),
        sa.Column("contraindications", sa.JSON(), nullable=False),
        sa.Column("requires_second_review", sa.Boolean(), nullable=False),
        sa.Column("second_reviewer_role", sa.String(length=40), nullable=True),
        sa.Column("override_policy", sa.JSON(), nullable=False),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["protocol_id"],
            ["institutional_clinical_protocols.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("protocol_id", "version"),
    )
    op.create_index(
        op.f("ix_institutional_clinical_protocol_versions_definition_hash"),
        "institutional_clinical_protocol_versions",
        ["definition_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_institutional_clinical_protocol_versions_id"),
        "institutional_clinical_protocol_versions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_institutional_clinical_protocol_versions_institution_id"),
        "institutional_clinical_protocol_versions",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_institutional_clinical_protocol_versions_protocol_id"),
        "institutional_clinical_protocol_versions",
        ["protocol_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_institutional_clinical_protocol_versions_review_status"),
        "institutional_clinical_protocol_versions",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_institutional_clinical_protocol_versions_status"),
        "institutional_clinical_protocol_versions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_institutional_clinical_protocol_versions_version"),
        "institutional_clinical_protocol_versions",
        ["version"],
        unique=False,
    )
    op.create_table(
        "medication_reconciliations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("pharmacist_user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("source_refs", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pharmacist_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_id", "idempotency_key"),
    )
    op.create_index(
        op.f("ix_medication_reconciliations_institution_id"),
        "medication_reconciliations",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_reconciliations_patient_id"),
        "medication_reconciliations",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_reconciliations_status"),
        "medication_reconciliations",
        ["status"],
        unique=False,
    )
    op.create_table(
        "medication_reconciliation_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reconciliation_id", sa.Integer(), nullable=False),
        sa.Column("medication_id", sa.Integer(), nullable=True),
        sa.Column("medication_name", sa.String(length=180), nullable=False),
        sa.Column("source_ref", sa.String(length=220), nullable=False),
        sa.Column("discrepancy", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=True),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.Column("author_user_id", sa.Integer(), nullable=True),
        sa.Column("formulation", sa.String(length=160), nullable=True),
        sa.Column("concentration", sa.String(length=120), nullable=True),
        sa.Column("history", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reconciliation_id"],
            ["medication_reconciliations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medication_reconciliation_items_medication_id"),
        "medication_reconciliation_items",
        ["medication_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_reconciliation_items_reconciliation_id"),
        "medication_reconciliation_items",
        ["reconciliation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_reconciliation_items_status"),
        "medication_reconciliation_items",
        ["status"],
        unique=False,
    )
    op.create_table(
        "pharmacy_interventions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("prescription_audit_id", sa.Integer(), nullable=True),
        sa.Column("medication_id", sa.Integer(), nullable=True),
        sa.Column("pharmacist_user_id", sa.Integer(), nullable=False),
        sa.Column("intervention_type", sa.String(length=60), nullable=False),
        sa.Column("severity", sa.String(length=40), nullable=False),
        sa.Column("priority", sa.String(length=40), nullable=False),
        sa.Column("problem", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("source_refs", sa.JSON(), nullable=False),
        sa.Column("dose_snapshot", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("cosignature_required", sa.Boolean(), nullable=False),
        sa.Column("cosigned_by_user_id", sa.Integer(), nullable=True),
        sa.Column("cosigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_actor_user_id", sa.Integer(), nullable=True),
        sa.Column("accepted", sa.Boolean(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cosigned_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pharmacist_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prescription_audit_id"],
            ["prescription_audits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_id", "idempotency_key"),
    )
    op.create_index(
        op.f("ix_pharmacy_interventions_id"), "pharmacy_interventions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_pharmacy_interventions_institution_id"),
        "pharmacy_interventions",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pharmacy_interventions_intervention_type"),
        "pharmacy_interventions",
        ["intervention_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pharmacy_interventions_medication_id"),
        "pharmacy_interventions",
        ["medication_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pharmacy_interventions_patient_id"),
        "pharmacy_interventions",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pharmacy_interventions_pharmacist_user_id"),
        "pharmacy_interventions",
        ["pharmacist_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pharmacy_interventions_prescription_audit_id"),
        "pharmacy_interventions",
        ["prescription_audit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pharmacy_interventions_priority"),
        "pharmacy_interventions",
        ["priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pharmacy_interventions_severity"),
        "pharmacy_interventions",
        ["severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pharmacy_interventions_status"), "pharmacy_interventions", ["status"], unique=False
    )
    op.create_table(
        "protocol_condition_scopes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("protocol_version_id", sa.Integer(), nullable=False),
        sa.Column("terminology_system", sa.String(length=80), nullable=False),
        sa.Column("terminology_version", sa.String(length=80), nullable=False),
        sa.Column("condition_code", sa.String(length=120), nullable=False),
        sa.Column("label", sa.String(length=220), nullable=False),
        sa.ForeignKeyConstraint(
            ["protocol_version_id"],
            ["institutional_clinical_protocol_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("protocol_version_id", "terminology_system", "condition_code"),
    )
    op.create_index(
        op.f("ix_protocol_condition_scopes_condition_code"),
        "protocol_condition_scopes",
        ["condition_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_protocol_condition_scopes_protocol_version_id"),
        "protocol_condition_scopes",
        ["protocol_version_id"],
        unique=False,
    )
    op.create_table(
        "protocol_credential_requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("protocol_version_id", sa.Integer(), nullable=False),
        sa.Column("credential_type", sa.String(length=80), nullable=False),
        sa.Column("credential_region", sa.String(length=20), nullable=True),
        sa.Column("verification_required", sa.Boolean(), nullable=False),
        sa.Column("unexpired_required", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["protocol_version_id"],
            ["institutional_clinical_protocol_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("protocol_version_id", "credential_type"),
    )
    op.create_index(
        op.f("ix_protocol_credential_requirements_protocol_version_id"),
        "protocol_credential_requirements",
        ["protocol_version_id"],
        unique=False,
    )
    op.create_table(
        "protocol_medication_scopes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("protocol_version_id", sa.Integer(), nullable=False),
        sa.Column("medication_id", sa.Integer(), nullable=False),
        sa.Column("concept_set_ref", sa.String(length=160), nullable=True),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["protocol_version_id"],
            ["institutional_clinical_protocol_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("protocol_version_id", "medication_id"),
    )
    op.create_index(
        op.f("ix_protocol_medication_scopes_medication_id"),
        "protocol_medication_scopes",
        ["medication_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_protocol_medication_scopes_protocol_version_id"),
        "protocol_medication_scopes",
        ["protocol_version_id"],
        unique=False,
    )
    op.create_table(
        "protocol_prescribing_scopes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("protocol_version_id", sa.Integer(), nullable=False),
        sa.Column("allowed_routes", sa.JSON(), nullable=False),
        sa.Column("dose_min", sa.Numeric(precision=24, scale=12), nullable=True),
        sa.Column("dose_max", sa.Numeric(precision=24, scale=12), nullable=True),
        sa.Column("dose_unit", sa.String(length=40), nullable=True),
        sa.Column("frequency_min_per_day", sa.Integer(), nullable=True),
        sa.Column("frequency_max_per_day", sa.Integer(), nullable=True),
        sa.Column("max_duration_days", sa.Integer(), nullable=True),
        sa.Column("min_age_years", sa.Integer(), nullable=True),
        sa.Column("max_age_years", sa.Integer(), nullable=True),
        sa.Column("min_weight_kg", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("max_weight_kg", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("constraints", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["protocol_version_id"],
            ["institutional_clinical_protocol_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_protocol_prescribing_scopes_protocol_version_id"),
        "protocol_prescribing_scopes",
        ["protocol_version_id"],
        unique=True,
    )
    op.create_table(
        "medication_formulation_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("intervention_id", sa.Integer(), nullable=True),
        sa.Column("reconciliation_item_id", sa.Integer(), nullable=True),
        sa.Column("reviewer_user_id", sa.Integer(), nullable=False),
        sa.Column("dose_input", sa.JSON(), nullable=False),
        sa.Column("formulation", sa.String(length=160), nullable=False),
        sa.Column("concentration", sa.String(length=120), nullable=False),
        sa.Column("rounding_policy", sa.String(length=80), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["intervention_id"],
            ["pharmacy_interventions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reconciliation_item_id"],
            ["medication_reconciliation_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medication_formulation_reviews_institution_id"),
        "medication_formulation_reviews",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_formulation_reviews_intervention_id"),
        "medication_formulation_reviews",
        ["intervention_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_formulation_reviews_reconciliation_item_id"),
        "medication_formulation_reviews",
        ["reconciliation_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_formulation_reviews_status"),
        "medication_formulation_reviews",
        ["status"],
        unique=False,
    )
    op.create_table(
        "pharmacy_intervention_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("intervention_id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("from_status", sa.String(length=40), nullable=True),
        sa.Column("to_status", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["intervention_id"],
            ["pharmacy_interventions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("intervention_id", "version"),
    )
    op.create_index(
        op.f("ix_pharmacy_intervention_events_event_type"),
        "pharmacy_intervention_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pharmacy_intervention_events_intervention_id"),
        "pharmacy_intervention_events",
        ["intervention_id"],
        unique=False,
    )
    op.add_column(
        "medications",
        sa.Column(
            "usual_dose_unit",
            sa.String(length=40),
            nullable=False,
            server_default="mg",
        ),
    )
    op.add_column(
        "medications",
        sa.Column(
            "usual_range_scope",
            sa.String(length=40),
            nullable=False,
            server_default="daily",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("medications", "usual_range_scope")
    op.drop_column("medications", "usual_dose_unit")
    op.drop_index(
        op.f("ix_pharmacy_intervention_events_intervention_id"),
        table_name="pharmacy_intervention_events",
    )
    op.drop_index(
        op.f("ix_pharmacy_intervention_events_event_type"),
        table_name="pharmacy_intervention_events",
    )
    op.drop_table("pharmacy_intervention_events")
    op.drop_index(
        op.f("ix_medication_formulation_reviews_status"),
        table_name="medication_formulation_reviews",
    )
    op.drop_index(
        op.f("ix_medication_formulation_reviews_reconciliation_item_id"),
        table_name="medication_formulation_reviews",
    )
    op.drop_index(
        op.f("ix_medication_formulation_reviews_intervention_id"),
        table_name="medication_formulation_reviews",
    )
    op.drop_index(
        op.f("ix_medication_formulation_reviews_institution_id"),
        table_name="medication_formulation_reviews",
    )
    op.drop_table("medication_formulation_reviews")
    op.drop_index(
        op.f("ix_protocol_prescribing_scopes_protocol_version_id"),
        table_name="protocol_prescribing_scopes",
    )
    op.drop_table("protocol_prescribing_scopes")
    op.drop_index(
        op.f("ix_protocol_medication_scopes_protocol_version_id"),
        table_name="protocol_medication_scopes",
    )
    op.drop_index(
        op.f("ix_protocol_medication_scopes_medication_id"), table_name="protocol_medication_scopes"
    )
    op.drop_table("protocol_medication_scopes")
    op.drop_index(
        op.f("ix_protocol_credential_requirements_protocol_version_id"),
        table_name="protocol_credential_requirements",
    )
    op.drop_table("protocol_credential_requirements")
    op.drop_index(
        op.f("ix_protocol_condition_scopes_protocol_version_id"),
        table_name="protocol_condition_scopes",
    )
    op.drop_index(
        op.f("ix_protocol_condition_scopes_condition_code"), table_name="protocol_condition_scopes"
    )
    op.drop_table("protocol_condition_scopes")
    op.drop_index(op.f("ix_pharmacy_interventions_status"), table_name="pharmacy_interventions")
    op.drop_index(op.f("ix_pharmacy_interventions_severity"), table_name="pharmacy_interventions")
    op.drop_index(op.f("ix_pharmacy_interventions_priority"), table_name="pharmacy_interventions")
    op.drop_index(
        op.f("ix_pharmacy_interventions_prescription_audit_id"), table_name="pharmacy_interventions"
    )
    op.drop_index(
        op.f("ix_pharmacy_interventions_pharmacist_user_id"), table_name="pharmacy_interventions"
    )
    op.drop_index(op.f("ix_pharmacy_interventions_patient_id"), table_name="pharmacy_interventions")
    op.drop_index(
        op.f("ix_pharmacy_interventions_medication_id"), table_name="pharmacy_interventions"
    )
    op.drop_index(
        op.f("ix_pharmacy_interventions_intervention_type"), table_name="pharmacy_interventions"
    )
    op.drop_index(
        op.f("ix_pharmacy_interventions_institution_id"), table_name="pharmacy_interventions"
    )
    op.drop_index(op.f("ix_pharmacy_interventions_id"), table_name="pharmacy_interventions")
    op.drop_table("pharmacy_interventions")
    op.drop_index(
        op.f("ix_medication_reconciliation_items_status"),
        table_name="medication_reconciliation_items",
    )
    op.drop_index(
        op.f("ix_medication_reconciliation_items_reconciliation_id"),
        table_name="medication_reconciliation_items",
    )
    op.drop_index(
        op.f("ix_medication_reconciliation_items_medication_id"),
        table_name="medication_reconciliation_items",
    )
    op.drop_table("medication_reconciliation_items")
    op.drop_index(
        op.f("ix_medication_reconciliations_status"), table_name="medication_reconciliations"
    )
    op.drop_index(
        op.f("ix_medication_reconciliations_patient_id"), table_name="medication_reconciliations"
    )
    op.drop_index(
        op.f("ix_medication_reconciliations_institution_id"),
        table_name="medication_reconciliations",
    )
    op.drop_table("medication_reconciliations")
    op.drop_index(
        op.f("ix_institutional_clinical_protocol_versions_version"),
        table_name="institutional_clinical_protocol_versions",
    )
    op.drop_index(
        op.f("ix_institutional_clinical_protocol_versions_status"),
        table_name="institutional_clinical_protocol_versions",
    )
    op.drop_index(
        op.f("ix_institutional_clinical_protocol_versions_review_status"),
        table_name="institutional_clinical_protocol_versions",
    )
    op.drop_index(
        op.f("ix_institutional_clinical_protocol_versions_protocol_id"),
        table_name="institutional_clinical_protocol_versions",
    )
    op.drop_index(
        op.f("ix_institutional_clinical_protocol_versions_institution_id"),
        table_name="institutional_clinical_protocol_versions",
    )
    op.drop_index(
        op.f("ix_institutional_clinical_protocol_versions_id"),
        table_name="institutional_clinical_protocol_versions",
    )
    op.drop_index(
        op.f("ix_institutional_clinical_protocol_versions_definition_hash"),
        table_name="institutional_clinical_protocol_versions",
    )
    op.drop_table("institutional_clinical_protocol_versions")
    op.drop_index(
        op.f("ix_institutional_clinical_protocols_status"),
        table_name="institutional_clinical_protocols",
    )
    op.drop_index(
        op.f("ix_institutional_clinical_protocols_program"),
        table_name="institutional_clinical_protocols",
    )
    op.drop_index(
        op.f("ix_institutional_clinical_protocols_institution_id"),
        table_name="institutional_clinical_protocols",
    )
    op.drop_index(
        op.f("ix_institutional_clinical_protocols_id"),
        table_name="institutional_clinical_protocols",
    )
    op.drop_index(
        op.f("ix_institutional_clinical_protocols_code"),
        table_name="institutional_clinical_protocols",
    )
    op.drop_table("institutional_clinical_protocols")
    # ### end Alembic commands ###
