"""research rwe evidence and ai foundation

Revision ID: 42168c1cc660
Revises: 3cebc8f0ba12
Create Date: 2026-08-07 23:51:51.646448
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "42168c1cc660"
down_revision: str | Sequence[str] | None = "3cebc8f0ba12"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concept_sets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("domain", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_user_id", sa.Integer(), nullable=True),
        sa.Column("current_version_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_id", "name", "domain"),
    )
    op.create_index(op.f("ix_concept_sets_domain"), "concept_sets", ["domain"], unique=False)
    op.create_index(
        op.f("ix_concept_sets_institution_id"), "concept_sets", ["institution_id"], unique=False
    )
    op.create_index(op.f("ix_concept_sets_name"), "concept_sets", ["name"], unique=False)
    op.create_index(op.f("ix_concept_sets_status"), "concept_sets", ["status"], unique=False)
    op.create_table(
        "data_quality_findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("rule", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=30), nullable=False),
        sa.Column("resource_type", sa.String(length=60), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("source", sa.String(length=160), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("resolution", sa.String(length=500), nullable=True),
        sa.Column("resolved_by_user_id", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_id", "rule", "resource_type", "resource_id", "field"),
    )
    op.create_index(
        op.f("ix_data_quality_findings_institution_id"),
        "data_quality_findings",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_quality_findings_resource_type"),
        "data_quality_findings",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_quality_findings_rule"), "data_quality_findings", ["rule"], unique=False
    )
    op.create_index(
        op.f("ix_data_quality_findings_severity"),
        "data_quality_findings",
        ["severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_quality_findings_status"), "data_quality_findings", ["status"], unique=False
    )
    op.create_table(
        "evidence_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("identifier", sa.String(length=180), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("publisher", sa.String(length=220), nullable=True),
        sa.Column("jurisdiction", sa.String(length=40), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("access_date", sa.Date(), nullable=True),
        sa.Column("source_version", sa.String(length=120), nullable=True),
        sa.Column("review_status", sa.String(length=40), nullable=False),
        sa.Column("reviewer_user_id", sa.Integer(), nullable=True),
        sa.Column("license_metadata", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_id", "identifier"),
    )
    op.create_index(
        op.f("ix_evidence_sources_identifier"), "evidence_sources", ["identifier"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_sources_institution_id"),
        "evidence_sources",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_sources_review_status"),
        "evidence_sources",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_sources_source_type"), "evidence_sources", ["source_type"], unique=False
    )
    op.create_table(
        "research_studies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("research_question", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("design", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("current_protocol_version_id", sa.String(length=36), nullable=True),
        sa.Column("demo_only", sa.Boolean(), nullable=False),
        sa.Column("data_source_classification", sa.String(length=40), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_id", "slug"),
    )
    op.create_index(
        op.f("ix_research_studies_design"), "research_studies", ["design"], unique=False
    )
    op.create_index(
        op.f("ix_research_studies_institution_id"),
        "research_studies",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_studies_owner_user_id"),
        "research_studies",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_research_studies_slug"), "research_studies", ["slug"], unique=False)
    op.create_index(
        op.f("ix_research_studies_status"), "research_studies", ["status"], unique=False
    )
    op.create_table(
        "ai_interactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=True),
        sa.Column("provider_model_identifier", sa.String(length=220), nullable=True),
        sa.Column("task_type", sa.String(length=80), nullable=False),
        sa.Column("prompt_template_version", sa.String(length=80), nullable=False),
        sa.Column("structured_schema_version", sa.String(length=80), nullable=False),
        sa.Column("source_ids", sa.JSON(), nullable=False),
        sa.Column("study_id", sa.String(length=36), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("output_hash", sa.String(length=64), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column("data_classification", sa.String(length=40), nullable=False),
        sa.Column("human_review_status", sa.String(length=40), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sanitized_error_class", sa.String(length=120), nullable=True),
        sa.Column("usage_metadata", sa.JSON(), nullable=False),
        sa.Column("output_payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["research_studies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_interactions_data_classification"),
        "ai_interactions",
        ["data_classification"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_interactions_human_review_status"),
        "ai_interactions",
        ["human_review_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_interactions_institution_id"),
        "ai_interactions",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_interactions_patient_id"), "ai_interactions", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_interactions_provider"), "ai_interactions", ["provider"], unique=False
    )
    op.create_index(op.f("ix_ai_interactions_status"), "ai_interactions", ["status"], unique=False)
    op.create_index(
        op.f("ix_ai_interactions_study_id"), "ai_interactions", ["study_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_interactions_task_type"), "ai_interactions", ["task_type"], unique=False
    )
    op.create_index(
        op.f("ix_ai_interactions_user_id"), "ai_interactions", ["user_id"], unique=False
    )
    op.create_table(
        "analysis_plans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("objectives", sa.JSON(), nullable=False),
        sa.Column("descriptive_metrics", sa.JSON(), nullable=False),
        sa.Column("subgroup_definitions", sa.JSON(), nullable=False),
        sa.Column("missing_data_approach", sa.Text(), nullable=False),
        sa.Column("methods", sa.JSON(), nullable=False),
        sa.Column("planned_outputs", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("authored_by_user_id", sa.Integer(), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["authored_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["research_studies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_id", "version"),
    )
    op.create_index(
        op.f("ix_analysis_plans_institution_id"), "analysis_plans", ["institution_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_plans_study_id"), "analysis_plans", ["study_id"], unique=False
    )
    op.create_table(
        "cohort_definitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("current_version_id", sa.String(length=36), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["research_studies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_id", "name"),
    )
    op.create_index(
        op.f("ix_cohort_definitions_institution_id"),
        "cohort_definitions",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cohort_definitions_status"), "cohort_definitions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_cohort_definitions_study_id"), "cohort_definitions", ["study_id"], unique=False
    )
    op.create_table(
        "concept_set_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("concept_set_id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("terminology_versions", sa.JSON(), nullable=False),
        sa.Column("include_descendants", sa.Boolean(), nullable=False),
        sa.Column("source_refs", sa.JSON(), nullable=False),
        sa.Column("license_metadata", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.Column("authored_by_user_id", sa.Integer(), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["authored_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["concept_set_id"],
            ["concept_sets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("concept_set_id", "version"),
    )
    op.create_index(
        op.f("ix_concept_set_versions_concept_set_id"),
        "concept_set_versions",
        ["concept_set_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_concept_set_versions_definition_hash"),
        "concept_set_versions",
        ["definition_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_concept_set_versions_institution_id"),
        "concept_set_versions",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_concept_set_versions_status"), "concept_set_versions", ["status"], unique=False
    )
    op.create_table(
        "covariate_definitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["research_studies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_covariate_definitions_institution_id"),
        "covariate_definitions",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_covariate_definitions_study_id"),
        "covariate_definitions",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "evidence_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("target_type", sa.String(length=60), nullable=False),
        sa.Column("target_id", sa.String(length=100), nullable=False),
        sa.Column("relationship", sa.String(length=80), nullable=False),
        sa.Column("locator", sa.String(length=220), nullable=False),
        sa.Column("review_status", sa.String(length=40), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["evidence_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "target_type", "target_id", "relationship", "locator"),
    )
    op.create_index(
        op.f("ix_evidence_links_institution_id"), "evidence_links", ["institution_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_links_source_id"), "evidence_links", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_links_target_id"), "evidence_links", ["target_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_links_target_type"), "evidence_links", ["target_type"], unique=False
    )
    op.create_table(
        "outcome_definitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("domain", sa.String(length=60), nullable=False),
        sa.Column("concept_set_version_ids", sa.JSON(), nullable=False),
        sa.Column("event_qualification", sa.JSON(), nullable=False),
        sa.Column("observation_window", sa.JSON(), nullable=False),
        sa.Column("temporal_relationship", sa.String(length=80), nullable=False),
        sa.Column("source_refs", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("review_status", sa.String(length=40), nullable=False),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.Column("authored_by_user_id", sa.Integer(), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["authored_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["research_studies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_id", "name", "version"),
    )
    op.create_index(
        op.f("ix_outcome_definitions_institution_id"),
        "outcome_definitions",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outcome_definitions_review_status"),
        "outcome_definitions",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outcome_definitions_study_id"), "outcome_definitions", ["study_id"], unique=False
    )
    op.create_table(
        "study_protocol_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("population", sa.JSON(), nullable=False),
        sa.Column("exposure", sa.JSON(), nullable=False),
        sa.Column("comparator", sa.JSON(), nullable=False),
        sa.Column("outcome", sa.JSON(), nullable=False),
        sa.Column("index_date", sa.JSON(), nullable=False),
        sa.Column("washout", sa.JSON(), nullable=False),
        sa.Column("follow_up", sa.JSON(), nullable=False),
        sa.Column("censoring", sa.JSON(), nullable=False),
        sa.Column("inclusion", sa.JSON(), nullable=False),
        sa.Column("exclusion", sa.JSON(), nullable=False),
        sa.Column("covariates", sa.JSON(), nullable=False),
        sa.Column("missing_data_strategy", sa.JSON(), nullable=False),
        sa.Column("statistical_plan", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("source_refs", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.Column("authored_by_user_id", sa.Integer(), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["authored_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["research_studies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_id", "version"),
    )
    op.create_index(
        op.f("ix_study_protocol_versions_definition_hash"),
        "study_protocol_versions",
        ["definition_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_protocol_versions_institution_id"),
        "study_protocol_versions",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_protocol_versions_status"),
        "study_protocol_versions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_protocol_versions_study_id"),
        "study_protocol_versions",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "cohort_definition_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cohort_definition_id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("query_cost", sa.Integer(), nullable=False),
        sa.Column("authored_by_user_id", sa.Integer(), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["authored_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cohort_definition_id"],
            ["cohort_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["research_studies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cohort_definition_id", "version"),
    )
    op.create_index(
        op.f("ix_cohort_definition_versions_cohort_definition_id"),
        "cohort_definition_versions",
        ["cohort_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cohort_definition_versions_definition_hash"),
        "cohort_definition_versions",
        ["definition_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cohort_definition_versions_institution_id"),
        "cohort_definition_versions",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cohort_definition_versions_status"),
        "cohort_definition_versions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cohort_definition_versions_study_id"),
        "cohort_definition_versions",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "concept_set_members",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("concept_set_version_id", sa.String(length=36), nullable=False),
        sa.Column("terminology_system", sa.String(length=40), nullable=False),
        sa.Column("terminology_version", sa.String(length=80), nullable=False),
        sa.Column("concept_id", sa.String(length=80), nullable=True),
        sa.Column("concept_code", sa.String(length=120), nullable=False),
        sa.Column("label", sa.String(length=240), nullable=False),
        sa.Column("excluded", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_set_version_id"],
            ["concept_set_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("concept_set_version_id", "terminology_system", "concept_code"),
    )
    op.create_index(
        op.f("ix_concept_set_members_concept_code"),
        "concept_set_members",
        ["concept_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_concept_set_members_concept_set_version_id"),
        "concept_set_members",
        ["concept_set_version_id"],
        unique=False,
    )
    op.create_table(
        "cohort_criteria",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cohort_version_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("group_type", sa.String(length=20), nullable=False),
        sa.Column("criterion", sa.String(length=60), nullable=False),
        sa.Column("operator", sa.String(length=20), nullable=True),
        sa.Column("field", sa.String(length=80), nullable=True),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("concept_set_version_id", sa.String(length=36), nullable=True),
        sa.Column("window", sa.JSON(), nullable=False),
        sa.Column("criterion_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_version_id"],
            ["cohort_definition_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["concept_set_version_id"],
            ["concept_set_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cohort_version_id", "sequence"),
    )
    op.create_index(
        op.f("ix_cohort_criteria_cohort_version_id"),
        "cohort_criteria",
        ["cohort_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cohort_criteria_concept_set_version_id"),
        "cohort_criteria",
        ["concept_set_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cohort_criteria_criterion"), "cohort_criteria", ["criterion"], unique=False
    )
    op.create_table(
        "cohort_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("study_id", sa.String(length=36), nullable=False),
        sa.Column("cohort_version_id", sa.String(length=36), nullable=False),
        sa.Column("protocol_version_id", sa.String(length=36), nullable=True),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("data_snapshot_marker", sa.String(length=160), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("executed_by_user_id", sa.Integer(), nullable=False),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.Column("source_version_refs", sa.JSON(), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("attrition", sa.JSON(), nullable=False),
        sa.Column("analytics", sa.JSON(), nullable=False),
        sa.Column("engine_version", sa.String(length=80), nullable=False),
        sa.Column("prescripta_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("run_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_version_id"],
            ["cohort_definition_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["executed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["protocol_version_id"],
            ["study_protocol_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["research_studies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cohort_runs_cohort_version_id"), "cohort_runs", ["cohort_version_id"], unique=False
    )
    op.create_index(
        op.f("ix_cohort_runs_definition_hash"), "cohort_runs", ["definition_hash"], unique=False
    )
    op.create_index(
        op.f("ix_cohort_runs_institution_id"), "cohort_runs", ["institution_id"], unique=False
    )
    op.create_index(
        op.f("ix_cohort_runs_protocol_version_id"),
        "cohort_runs",
        ["protocol_version_id"],
        unique=False,
    )
    op.create_index(op.f("ix_cohort_runs_run_hash"), "cohort_runs", ["run_hash"], unique=False)
    op.create_index(op.f("ix_cohort_runs_status"), "cohort_runs", ["status"], unique=False)
    op.create_index(op.f("ix_cohort_runs_study_id"), "cohort_runs", ["study_id"], unique=False)
    op.create_table(
        "cohort_run_steps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cohort_run_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("criterion", sa.JSON(), nullable=False),
        sa.Column("label", sa.String(length=240), nullable=False),
        sa.Column("before_count", sa.Integer(), nullable=False),
        sa.Column("excluded_count", sa.Integer(), nullable=False),
        sa.Column("after_count", sa.Integer(), nullable=False),
        sa.Column("criterion_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_run_id"],
            ["cohort_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cohort_run_id", "sequence"),
    )
    op.create_index(
        op.f("ix_cohort_run_steps_cohort_run_id"),
        "cohort_run_steps",
        ["cohort_run_id"],
        unique=False,
    )
    op.create_table(
        "research_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cohort_run_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_type", sa.String(length=60), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_run_id"],
            ["cohort_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_snapshots_cohort_run_id"),
        "research_snapshots",
        ["cohort_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_snapshots_snapshot_hash"),
        "research_snapshots",
        ["snapshot_hash"],
        unique=False,
    )
    with op.batch_alter_table("patient_clinical_timeline_events") as batch_op:
        batch_op.add_column(
            sa.Column(
                "institution_id",
                sa.String(length=100),
                nullable=False,
                server_default="demo",
            )
        )
        batch_op.add_column(sa.Column("source_ref", sa.String(length=220)))
        batch_op.add_column(sa.Column("concept_system", sa.String(length=40)))
        batch_op.add_column(sa.Column("concept_code", sa.String(length=120)))
        batch_op.add_column(sa.Column("concept_label", sa.String(length=240)))
        batch_op.add_column(sa.Column("provenance", sa.JSON(), nullable=False, server_default="{}"))
        batch_op.add_column(
            sa.Column(
                "visibility_classification",
                sa.String(length=40),
                nullable=False,
                server_default="clinical",
            )
        )
        batch_op.create_index(
            "ix_patient_clinical_timeline_events_concept_code",
            ["concept_code"],
        )
        batch_op.create_index(
            "ix_patient_clinical_timeline_events_institution_id",
            ["institution_id"],
        )
        batch_op.create_unique_constraint(
            "uq_patient_clinical_timeline_source_ref",
            ["institution_id", "source_ref"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient_clinical_timeline_events") as batch_op:
        batch_op.drop_constraint(
            "uq_patient_clinical_timeline_source_ref",
            type_="unique",
        )
        batch_op.drop_index("ix_patient_clinical_timeline_events_institution_id")
        batch_op.drop_index("ix_patient_clinical_timeline_events_concept_code")
        for column in (
            "visibility_classification",
            "provenance",
            "concept_label",
            "concept_code",
            "concept_system",
            "source_ref",
            "institution_id",
        ):
            batch_op.drop_column(column)
    op.drop_index(op.f("ix_research_snapshots_snapshot_hash"), table_name="research_snapshots")
    op.drop_index(op.f("ix_research_snapshots_cohort_run_id"), table_name="research_snapshots")
    op.drop_table("research_snapshots")
    op.drop_index(op.f("ix_cohort_run_steps_cohort_run_id"), table_name="cohort_run_steps")
    op.drop_table("cohort_run_steps")
    op.drop_index(op.f("ix_cohort_runs_study_id"), table_name="cohort_runs")
    op.drop_index(op.f("ix_cohort_runs_status"), table_name="cohort_runs")
    op.drop_index(op.f("ix_cohort_runs_run_hash"), table_name="cohort_runs")
    op.drop_index(op.f("ix_cohort_runs_protocol_version_id"), table_name="cohort_runs")
    op.drop_index(op.f("ix_cohort_runs_institution_id"), table_name="cohort_runs")
    op.drop_index(op.f("ix_cohort_runs_definition_hash"), table_name="cohort_runs")
    op.drop_index(op.f("ix_cohort_runs_cohort_version_id"), table_name="cohort_runs")
    op.drop_table("cohort_runs")
    op.drop_index(op.f("ix_cohort_criteria_criterion"), table_name="cohort_criteria")
    op.drop_index(op.f("ix_cohort_criteria_concept_set_version_id"), table_name="cohort_criteria")
    op.drop_index(op.f("ix_cohort_criteria_cohort_version_id"), table_name="cohort_criteria")
    op.drop_table("cohort_criteria")
    op.drop_index(
        op.f("ix_concept_set_members_concept_set_version_id"), table_name="concept_set_members"
    )
    op.drop_index(op.f("ix_concept_set_members_concept_code"), table_name="concept_set_members")
    op.drop_table("concept_set_members")
    op.drop_index(
        op.f("ix_cohort_definition_versions_study_id"), table_name="cohort_definition_versions"
    )
    op.drop_index(
        op.f("ix_cohort_definition_versions_status"), table_name="cohort_definition_versions"
    )
    op.drop_index(
        op.f("ix_cohort_definition_versions_institution_id"),
        table_name="cohort_definition_versions",
    )
    op.drop_index(
        op.f("ix_cohort_definition_versions_definition_hash"),
        table_name="cohort_definition_versions",
    )
    op.drop_index(
        op.f("ix_cohort_definition_versions_cohort_definition_id"),
        table_name="cohort_definition_versions",
    )
    op.drop_table("cohort_definition_versions")
    op.drop_index(op.f("ix_study_protocol_versions_study_id"), table_name="study_protocol_versions")
    op.drop_index(op.f("ix_study_protocol_versions_status"), table_name="study_protocol_versions")
    op.drop_index(
        op.f("ix_study_protocol_versions_institution_id"), table_name="study_protocol_versions"
    )
    op.drop_index(
        op.f("ix_study_protocol_versions_definition_hash"), table_name="study_protocol_versions"
    )
    op.drop_table("study_protocol_versions")
    op.drop_index(op.f("ix_outcome_definitions_study_id"), table_name="outcome_definitions")
    op.drop_index(op.f("ix_outcome_definitions_review_status"), table_name="outcome_definitions")
    op.drop_index(op.f("ix_outcome_definitions_institution_id"), table_name="outcome_definitions")
    op.drop_table("outcome_definitions")
    op.drop_index(op.f("ix_evidence_links_target_type"), table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_target_id"), table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_source_id"), table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_institution_id"), table_name="evidence_links")
    op.drop_table("evidence_links")
    op.drop_index(op.f("ix_covariate_definitions_study_id"), table_name="covariate_definitions")
    op.drop_index(
        op.f("ix_covariate_definitions_institution_id"), table_name="covariate_definitions"
    )
    op.drop_table("covariate_definitions")
    op.drop_index(op.f("ix_concept_set_versions_status"), table_name="concept_set_versions")
    op.drop_index(op.f("ix_concept_set_versions_institution_id"), table_name="concept_set_versions")
    op.drop_index(
        op.f("ix_concept_set_versions_definition_hash"), table_name="concept_set_versions"
    )
    op.drop_index(op.f("ix_concept_set_versions_concept_set_id"), table_name="concept_set_versions")
    op.drop_table("concept_set_versions")
    op.drop_index(op.f("ix_cohort_definitions_study_id"), table_name="cohort_definitions")
    op.drop_index(op.f("ix_cohort_definitions_status"), table_name="cohort_definitions")
    op.drop_index(op.f("ix_cohort_definitions_institution_id"), table_name="cohort_definitions")
    op.drop_table("cohort_definitions")
    op.drop_index(op.f("ix_analysis_plans_study_id"), table_name="analysis_plans")
    op.drop_index(op.f("ix_analysis_plans_institution_id"), table_name="analysis_plans")
    op.drop_table("analysis_plans")
    op.drop_index(op.f("ix_ai_interactions_user_id"), table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_task_type"), table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_study_id"), table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_status"), table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_provider"), table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_patient_id"), table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_institution_id"), table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_human_review_status"), table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_data_classification"), table_name="ai_interactions")
    op.drop_table("ai_interactions")
    op.drop_index(op.f("ix_research_studies_status"), table_name="research_studies")
    op.drop_index(op.f("ix_research_studies_slug"), table_name="research_studies")
    op.drop_index(op.f("ix_research_studies_owner_user_id"), table_name="research_studies")
    op.drop_index(op.f("ix_research_studies_institution_id"), table_name="research_studies")
    op.drop_index(op.f("ix_research_studies_design"), table_name="research_studies")
    op.drop_table("research_studies")
    op.drop_index(op.f("ix_evidence_sources_source_type"), table_name="evidence_sources")
    op.drop_index(op.f("ix_evidence_sources_review_status"), table_name="evidence_sources")
    op.drop_index(op.f("ix_evidence_sources_institution_id"), table_name="evidence_sources")
    op.drop_index(op.f("ix_evidence_sources_identifier"), table_name="evidence_sources")
    op.drop_table("evidence_sources")
    op.drop_index(op.f("ix_data_quality_findings_status"), table_name="data_quality_findings")
    op.drop_index(op.f("ix_data_quality_findings_severity"), table_name="data_quality_findings")
    op.drop_index(op.f("ix_data_quality_findings_rule"), table_name="data_quality_findings")
    op.drop_index(
        op.f("ix_data_quality_findings_resource_type"), table_name="data_quality_findings"
    )
    op.drop_index(
        op.f("ix_data_quality_findings_institution_id"), table_name="data_quality_findings"
    )
    op.drop_table("data_quality_findings")
    op.drop_index(op.f("ix_concept_sets_status"), table_name="concept_sets")
    op.drop_index(op.f("ix_concept_sets_name"), table_name="concept_sets")
    op.drop_index(op.f("ix_concept_sets_institution_id"), table_name="concept_sets")
    op.drop_index(op.f("ix_concept_sets_domain"), table_name="concept_sets")
    op.drop_table("concept_sets")
    # ### end Alembic commands ###
